version: '3.8'

services:
  mail-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: wazami-mail-worker
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - UPSTASH_REDIS_URL=${UPSTASH_REDIS_URL}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - WORKER_CONCURRENCY=5
    volumes:
      - ./logs:/app/logs
    networks:
      - mail-network
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  mail-network:
    driver: bridge
